version: '3.7'
services:
  plugin:
    restart: always
    image: cyberreboot/dovesnap
    build:
      context: .
    volumes:
      - /run/docker/plugins:/run/docker/plugins
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/var/run/openvswitch:/var/run/openvswitch
      - /opt/dovesnap/faucetconfrpc:/faucetconfrpc
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    command: -d
    depends_on:
      - ovs
    command:
      - -d
      - --faucetconfrpc_addr=localhost
      - --faucetconfrpc_port=59999
      - --faucetconfrpc_keydir=/faucetconfrpc
  ovs:
    restart: always
    image: cyberreboot/openvswitch:v2.13.0
    volumes:
      - /usr/local/var/run/openvswitch:/usr/local/var/run/openvswitch
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
