version: '3.7'
services:
  faucet:
    restart: always
    image: 'faucet/faucet:1.9.47'
    networks:
      - dovesnap
    volumes:
      - /var/log/faucet:/var/log/faucet
      - '${FAUCET_PREFIX}/etc/faucet:/etc/faucet'
    ports:
      - '6653:6653'
    environment:
      FAUCET_CONFIG_STAT_RELOAD: '1'
      FAUCET_CONFIG_AUTO_REVERT: '1'
  gauge:
    restart: always
    image: 'faucet/gauge:1.9.47'
    networks:
      - dovesnap
    volumes:
      - /var/log/gauge:/var/log/gauge
      - '${FAUCET_PREFIX}/etc/faucet:/etc/faucet'
    ports:
      - '6654:6654'
    environment:
      GAUGE_CONFIG_STAT_RELOAD: '1'
      GAUGE_CONFIG_AUTO_REVERT: '1'
  faucet_certstrap:
    restart: on-failure
    image: 'cyberreboot/faucet-certstrap:v0.14.2'
    network_mode: none
    volumes:
      - /opt/dovesnap:/opt/dovesnap
    command:
      - /opt/dovesnap/faucetconfrpc
      - localhost
  faucetconfrpc:
    restart: always
    image: 'cyberreboot/faucetconfrpc:v0.13'
    environment:
      PYTHONUNBUFFERED: '1'
    networks:
      - dovesnap
    volumes:
      - /opt/dovesnap/faucetconfrpc:/faucetconfrpc
      - '${FAUCET_PREFIX}/etc/faucet:/etc/faucet'
    ports:
      - 59999:59999
    command:
      - --key=/faucetconfrpc/localhost.key
      - --cert=/faucetconfrpc/localhost.crt
      - --cacert=/faucetconfrpc/localhost-ca.crt
      - --host=0.0.0.0
      - --config_dir=/etc/faucet
    depends_on:
      - faucet
      - gauge
networks:
    dovesnap:
