plugin:
  build: .
  volumes:
    - /run/docker/plugins/ovs.sock:/run/docker/plugins/ovs.sock
    - /var/run/docker.sock:/var/run/docker.sock
  net: host
  privileged: true

ovs:
  image: socketplane/openvswitch:2.3.2
  cap_add: NET_ADMIN
  net: host
