[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "0.8.7"

[[constraint]]
  branch = "master"
  name = "github.com/docker/go-plugins-helpers"

[[constraint]]
  name = "github.com/iqtlabs/faucetconfrpc"
  version = "0.14"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/docker/docker"
  version = "18.9.9"
