[[constraint]]
  branch = "master"
  name = "github.com/docker/go-plugins-helpers"

[[constraint]]
  name = "github.com/iqtlabs/faucetconfrpc"
  version = "0.21"

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/docker/docker"
  source = "https://github.com/docker/engine"
  version = "19.03.12"
