name: test

on: [push, pull_request]

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: go format
      run: ./codecheck.sh
  standalone_int_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: standalone_int_test
      run: |
        ./install_test.sh && ./test_dovesnap_standalone.sh
  stack_int_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: stack_int_test
      run: |
        ./install_test.sh && ./test_dovesnap_stack.sh
  mirrorbridge_int_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: mirrorbridge_int_test
      run: |
        ./install_test.sh && ./test_dovesnap_mirrorbridge.sh
  dhcp_int_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: mirrorbridge_int_test
      run: |
        ./install_test.sh && ./test_dovesnap_dhcp.sh
