name: test

on: [push, pull_request]

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: go format
      run: ./codecheck.sh
  standalone_int_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: standalone_int_test
      run: |
        sudo modprobe openvswitch && \
        sudo modprobe 8021q && \
        export DEBIAN_FRONTEND=noninteractive && \
        echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
        sudo apt-get update && \
        sudo apt-get remove docker docker-engine docker.io containerd runc python3-yaml && \
        sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common && \
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
        sudo apt-get update && sudo apt-get install docker-ce docker-ce-cli containerd.io wget && \
        ./test_dovesnap_standalone.sh
  stack_int_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: stack_int_test
      run: |
        sudo modprobe openvswitch && \
        sudo modprobe 8021q && \
        export DEBIAN_FRONTEND=noninteractive && \
        echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
        sudo apt-get update && \
        sudo apt-get remove docker docker-engine docker.io containerd runc python3-yaml && \
        sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common && \
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
        sudo apt-get update && sudo apt-get install docker-ce docker-ce-cli containerd.io wget && \
        ./test_dovesnap_stack.sh
  mirrorbridge_int_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: mirrorbridge_int_test
      run: |
        sudo modprobe openvswitch && \
        sudo modprobe 8021q && \
        export DEBIAN_FRONTEND=noninteractive && \
        echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
        sudo apt-get update && \
        sudo apt-get remove docker docker-engine docker.io containerd runc python3-yaml && \
        sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common && \
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
        sudo apt-get update && sudo apt-get install docker-ce docker-ce-cli containerd.io wget && \
        ./test_dovesnap_mirrorbridge.sh
