name: test

on: [push, pull_request]

jobs:
  test:
    - name: int_test
      run: |
        export DEBIAN_FRONTEND=noninteractive && \
        echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
        sudo apt-get update && \
        sudo apt-get remove docker docker-engine docker.io containerd runc && \
        sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common && \
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
        sudo apt-get update && sudo apt-get install docker-ce docker-ce-cli containerd.io && \
        pip3 install -U pip && \
        pip3 install faucet && \
        ./test_dovesnap.sh
