name: test

on: [push, pull_request]

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: go format
        uses: actions/checkout@v2
        run: ./tests/codecheck.sh
  standalone_noconfig_int_test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: standalone_noconfig_int_test
        uses: actions/checkout@v2
        run: |
          ./tests/install_test.sh && timeout 600 ./tests/test_dovesnap_standalone_noconfig.sh
  standalone_int_test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: standalone_int_test
        uses: actions/checkout@v2
        run: |
          ./tests/install_test.sh && timeout 600 ./tests/test_dovesnap_standalone.sh
  stack_int_test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: stack_int_test
        uses: actions/checkout@v2
        run: |
          ./tests/install_test.sh && timeout 600 ./tests/test_dovesnap_stack.sh
  mirrorbridge_int_test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: mirrorbridge_int_test
        uses: actions/checkout@v2
        run: |
          ./tests/install_test.sh && timeout 600 ./tests/test_dovesnap_mirrorbridge.sh
  dhcp_int_test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: dhcp_int_test
        uses: actions/checkout@v2
        run: |
          ./tests/install_test.sh && ./tests/test_dovesnap_dhcp.sh
